# Example of verifying an pth model with VNNLIB general specifications
general:
  enable_incomplete_verification: false
  loss_reduction_func: max
  save_adv_example: True
model:
  name: sac_discrete2d_2_32
  path: /app/discrete/hovering_sac_kin_discrete2d.pth
  input_shape: [-1, 12]
specification:
  # VNNLIB file specification.
  vnnlib_path: /app/discrete/prop_eps01_never_left.vnnlib
solver:
  batch_size: 1028  # Number of subdomains to compute in parallel in bound solver. Decrease if you run out of memory.
bab:
  timeout: 340 
attack:
  pgd_order: before
  cex_path: /app/discrete/adv_sac_discrete_never_left.txt